spring:
  application:
    name: BooksSpringBootAdmin

  security:
    user:
      name: testuser
      password: testpass

  boot:
    admin:
      notify:
        mail:
          enabled: false
      #discovery:
      #  ignored-services: BooksSpringBootAdmin

  cloud:
    loadbalancer:
      ribbon:
        enabled: false    # RibbonLoadBalancerClient deprecated. This setting uses BlockingLoadBalancerClient

server:
  port: 8888

jwt:
  token:
    actuator:
      user: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJMT0NBTF9BQ1RVQVRPUl9VU0VSIiwiaXNzIjoiQ2xvdWR5Qm9va0NsdWIiLCJwcm92aWRlciI6IkxPQ0FMIiwibmFtZSI6IkFjdHVhdG9yIFVzZXIiLCJyb2xlcyI6IjIiLCJpYXQiOjE2OTY3ODY4NDAsImV4cCI6MTcyODMyMjg0MH0.opC3bWIaV6jKreyqs57-OwvQI4aOdMt3-JYoDYznezW7sf-Gd0bzOtXCNJHKLAYJU4HsJgTBGMExCRNPJlZNgQ
eureka:
  instance:
    hostname: localhost
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        # Exposing only read only items and not large data amounts - so no heapdump, threaddump or shutdown. No project use of flyway, integrationgraph, liquibase, prometheus
        include: auditevents, beans, caches, conditions, configprops, env, health, httptrace, info, jolokia, logfile, loggers, metrics, mappings, scheduledtasks, sessions
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false
